<Login>:
    FloatLayout:

        Label:
            text: 'Operating mode name:'
            font_size: "35dp"
            size_hint: 0.06, 0.1
            pos_hint: {'center_x': 0.15, 'center_y':0.7}

        TextInput:
            id: login
            multiline: True
            font_size: "35dp"
            size_hint: 0.58, 0.126
            pos_hint: {'x': 0.30, 'y':0.64}

        Button:
            text: 'Save'
            size_hint: 0.09, 0.1
            pos_hint: {'center_x': 0.92, 'center_y':0.66}
            font_size: 30
            on_press: root.do_login(loginText)